version: '3.6'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
    - 8080:8080
    command: start-dev