version: '3.6'

volumes:
  keycloak-data:
    external: true

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    volumes:
      - keycloak-data:/data
    ports:
    - 8080:8080
    - 8443:8443
    - 9000:9000
    command: start-dev